# version format
version: 0.0.{build}

cache:
  - C:\projects\downloads

# scripts that are called at very beginning, before repo cloning
init:
  - date /T & time /T
  - git config --global core.autocrlf input

before_build: 
  - build-scripts\1-download.bat
  - dir C:\projects /s

build_script:
  - build-tools\innosetup\iscc /DAPP_VERSION=%APPVEYOR_BUILD_VERSION% installer\fife-sdk.iss

after_build:
  - dir C:\projects\_build /s
  - appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\_build\FifeSDK-%APPVEYOR_BUILD_VERSION%-Setup-VC14-x86.exe"

